import os

from dotenv import load_dotenv
from google import genai


load_dotenv()


class GeminiService:

    def __init__(self):
        self.api_key = os.getenv("GEMINI_API_KEY")
        self.model = os.getenv(
            "GEMINI_MODEL",
            "gemini-2.5-flash",
        )

        if not self.api_key:
            raise ValueError(
                "GEMINI_API_KEY is not configured in .env"
            )

        self.client = genai.Client(
            api_key=self.api_key
        )

    def generate_response(self, prompt: str) -> str:

        response = self.client.models.generate_content(
            model=self.model,
            contents=prompt,
        )

        return response.text
    
    def generate_grounded_response(
        self,
        query: str,
        context: str,
    ) -> str:

        prompt = f"""
    You are an AI decision intelligence system for an energy
    supply-chain resilience platform.

    Use the supplied knowledge context to analyse the situation.

    KNOWLEDGE CONTEXT:
    {context}

    USER / SYSTEM QUERY:
    {query}

    Provide:
    1. Risk assessment
    2. Recommended mitigation strategy
    3. Reason for the recommendation
    4. Expected operational impact

    Base your recommendation primarily on the supplied context.
    Do not invent routes or operational data that are not supported
    by the context.
    """

        response = self.client.models.generate_content(
            model=self.model,
            contents=prompt,
        )

        return response.text
    
    def analyze_news_risk(
        self,
        title: str,
        description: str,
        source: str = "Unknown",
    ) -> str:
        """
        Analyze a live news article for energy supply-chain risk.
        Returns structured JSON generated by Gemini.
        """

        prompt = f"""
You are an AI geopolitical and energy supply-chain
risk intelligence analyst.

Analyze the following live news article.

SOURCE:
{source}

TITLE:
{title}

DESCRIPTION:
{description}

Determine whether this event could affect energy supply chains,
oil and gas transportation, ports, shipping routes, suppliers,
refineries, commodity availability, or India's energy security.

Return ONLY valid JSON.

Do not include markdown.
Do not include ```json.
Do not include explanations outside the JSON.

Use exactly this structure:

{{
    "severity": "low | medium | high | critical",
    "category": "event classification",
    "entities": ["relevant entities"],
    "countries": ["affected countries"],
    "ports": ["affected ports"],
    "routes": ["affected shipping routes or corridors"],
    "impact": "concise potential impact on India and energy supply chains",
    "priority": "Low | Medium | High | Critical",
    "risk_score": 0
}}

The risk_score must be an integer between 0 and 100.

Severity guidance:
0-29 = low
30-59 = medium
60-79 = high
80-100 = critical.

If a port, route, country, or entity cannot be reasonably
identified from the article, return an empty array instead of
inventing information.
"""

        response = self.client.models.generate_content(
            model=self.model,
            contents=prompt,
        )

        return response.text    


gemini_service = GeminiService()